# Generated by Django 5.1.2 on 2024-11-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_coursestudentrelationship_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursestudentrelationship',
            unique_together={('student', 'course', 'semester')},
        ),
    ]
