# Generated by Django 5.1.2 on 2024-11-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_coursestudentrelationship_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursestudentrelationship',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coursestudentrelationship',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'semester'), name='unique_student_course_semester', violation_error_message='This student is already enrolled in this course for the given semester.'),
        ),
    ]
