# Generated by Django 5.1.2 on 2024-11-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_coursestudentrelationship_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursestudentrelationship',
            name='unique_student_course_semester',
        ),
        migrations.AlterUniqueTogether(
            name='coursestudentrelationship',
            unique_together={('student', 'course', 'semester')},
        ),
    ]
